---
version: "3.0"
services:
  little-link:
    image: ghcr.io/techno-tim/littlelink-server:latest
    container_name: littlelink-server
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - META_TITLE=Paula Aguilar
      - META_DESCRIPTION=El arte de la cocinar
      - META_AUTHOR=Paula Aguilar
      - META_KEYWORDS=Bocados Sabrosos, Delicias Culinarias, Recetas Rápidas, Cocina
      - LANG=es
      - META_INDEX_STATUS=all
      - THEME=Light
      - FAVICON_URL=https://www.paulaguilar.es/wp-content/uploads/2024/03/cropped-logo-simple-marron-192x192.png
      - AVATAR_URL=https://www.paulaguilar.es/wp-content/uploads/2024/03/cropped-logo-simple-marron-192x192.png
      - AVATAR_2X_URL=https://www.paulaguilar.es/wp-content/uploads/2024/03/cropped-logo-simple-marron-192x192.png
      - AVATAR_ALT=Paula Aguilar Profile Pic
      - NAME=Paula Aguilar
      - BIO=👩‍🍳Saborea el arte de la cocina👩‍🍳
      - FOOTER=👋🌟¡Gracias por su visita!🌟👋

      - OG_SITE_NAME=Paula Aguilar
      - OG_TITLE=👩‍🍳 Saborea el arte de la cocina 👩‍🍳
      - OG_DESCRIPTION=⬇️ Enlaces interesantes ⬇️
      - OG_URL=https://links.paulaguilar.es
      - OG_IMAGE=https://www.paulaguilar.es/wp-content/uploads/2024/03/logo-open-graph-resize.png
      - OG_IMAGE_WIDTH=500
      - OG_IMAGE_HEIGHT=321

      - SHARE=https://links.paulaguilar.es

      - CUSTOM_BUTTON_TEXT=Libro de recetas
      - CUSTOM_BUTTON_URL=https://paulaguilar.es
      - CUSTOM_BUTTON_COLOR=#ffffff
      - CUSTOM_BUTTON_TEXT_COLOR=#b29079
      - CUSTOM_BUTTON_ALT_TEXT=Enlace de página web con recetas de Paula Aguilar
      - CUSTOM_BUTTON_NAME=¡Visita mi página web!
      - CUSTOM_BUTTON_ICON=fas receipt

      - YOUTUBE=https://youtube.com/@paula.art.cooking
      - TWITTER=https://twitter.com/pau_art_cooking
      - INSTAGRAM=https://instagram.com/paula.art.cooking/
      - TIKTOK=https://tiktok.com/@paula.art.cooking
      - EMAIL=paulaguilarcooking@gmail.com
      - EMAIL_TEXT=Contacto

      - UMAMI_WEBSITE_ID=a7d437c4-c2c7-48c4-8935-788f94d89925
      - UMAMI_APP_URL=https://analytics.eu.umami.is
      - UMAMI_SCRIPT_NAME=script.js

      # - PINTEREST=https://www.pinterest.com/
      # - FACEBOOK=https://facebook.com
      # - SNAPCHAT=https://www.snapchat.com/
      # - TELEGRAM=https://telegram.org/
      # - WHATSAPP=https://www.whatsapp.com/
      # - AMAZON_AFFILIATE=https://affiliate-program.amazon.co.uk/
      # - X=https://x.com
      
     
    ports:
      - 8080:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
